[package]
name = "candle_server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
serde = {version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = {version = "1.28.1", features = ["full"] }
tokio-tungstenite = "0.19.0"
url = "2.3.1"
